"""Vendor-neutral domain contracts and repository interfaces."""

from qfusion.domain.contracts import (
    MARKET_TIMEZONES,
    AnalysisSnapshot,
    DataSourceRecord,
    FactQuery,
    Market,
    QualityFlag,
    RequestedHorizon,
    TargetType,
    require_point_in_time,
)
from qfusion.domain.instruments import (
    EffectiveIdentifier,
    EffectiveLookup,
    Instrument,
    InstrumentAssetType,
    InstrumentQuery,
    ProviderIdentifierLookup,
    ProviderInstrumentMapping,
    ProviderMappingLookup,
    TickerAlias,
    TickerLookup,
    require_instrument_available,
    require_provider_identifier_match,
    require_provider_mapping_match,
    require_ticker_match,
)
from qfusion.domain.repositories import (
    FactReadRepository,
    InstrumentRegistryRepository,
    SnapshotRepository,
)

__all__ = [
    "MARKET_TIMEZONES",
    "AnalysisSnapshot",
    "DataSourceRecord",
    "EffectiveIdentifier",
    "EffectiveLookup",
    "FactQuery",
    "FactReadRepository",
    "Instrument",
    "InstrumentAssetType",
    "InstrumentQuery",
    "InstrumentRegistryRepository",
    "Market",
    "ProviderIdentifierLookup",
    "ProviderInstrumentMapping",
    "ProviderMappingLookup",
    "QualityFlag",
    "RequestedHorizon",
    "SnapshotRepository",
    "TargetType",
    "TickerAlias",
    "TickerLookup",
    "require_instrument_available",
    "require_point_in_time",
    "require_provider_identifier_match",
    "require_provider_mapping_match",
    "require_ticker_match",
]
